function Top_Default()
{
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr><td background='http://www.netland.com.cn/images/Top_BG.jpg'>");
	document.write("<table width='100%' border='0' cellpadding='0' cellspacing='0'>");
	document.write("<tr>");
	document.write("<td width='160' align='center'><img src='http://www.netland.com.cn/images/Top_Logo.gif' width='140' height='88'></td>");
	document.write("<td valign='bottom'>");
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='84' height='23' align='center' background='http://www.netland.com.cn/images/BG_MenuGray.gif' style='padding-top:4px'>");
	document.write("<a href='/'><font color='#FFFFFF'>首 页</font></a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Market/'>今日报价</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/News/'>资讯中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Products/Default.asp'>产品中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8' style='padding-top:4px'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Tech/'>技术天地</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Trainning/'>培训认证</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Down/'>下载中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='7'><img src='http://www.netland.com.cn/images/BG_Menu_01.gif' width='7' height='23'></td>");
	document.write("<td background='http://www.netland.com.cn/images/BG_Menu_02.gif'>&nbsp;</td>");
	document.write("</tr>");
	document.write("</table></td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td height='22' valign='top' background='http://www.netland.com.cn/images/Top_GrayBar.gif' style='padding-top:3px'>");
	document.write("<table border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='190'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='15'></td>");
	document.write("<td>");	
	document.write("<a href='/Products/Products_AllClass.asp'><font color='#FFFFFF'>产品分类</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Products/Products_AllBrand.asp'><font color='#FFFFFF'>品牌列表</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Tech/Tech_Class.asp?CateID=15' target='_blank'><font color='#FFFFFF'>产品导购</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Down/Down_Driver.asp'><font color='#FFFFFF'>驱动下载</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Tech/Tech_Solu.asp'><font color='#FFFFFF'>解决方案</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Trainning/'><font color='#FFFFFF'>华为3Com培训</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='http://www.vavic.com/VavicTime/' target='_blank'><font color='#FFFFFF'>《网域》期刊</font></a>");
	document.write("</td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td bgcolor='#FFFFFF'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='1'></td></tr>");
	document.write("</table>");
}

function Top_Products()
{
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr><td background='http://www.netland.com.cn/images/Top_BG.jpg'>");
	document.write("<table width='100%' border='0' cellpadding='0' cellspacing='0'>");
	document.write("<tr>");
	document.write("<td width='160' align='center'><img src='http://www.netland.com.cn/images/Top_Logo.gif' width='140' height='88'></td>");
	document.write("<td valign='bottom'>");
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='84' height='23' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/'>首 页</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Market/'>今日报价</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/News/'>资讯中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_MenuGray.gif' style='padding-top:4px'>");
	document.write("<a href='/Products/Default.asp'><font color='#FFFFFF'>产品中心</font></a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8' style='padding-top:4px'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Tech/'>技术天地</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Trainning/'>培训认证</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Down/'>下载中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='7'><img src='http://www.netland.com.cn/images/BG_Menu_01.gif' width='7' height='23'></td>");
	document.write("<td background='http://www.netland.com.cn/images/BG_Menu_02.gif'>&nbsp;</td>");
	document.write("</tr>");
	document.write("</table></td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td height='22' valign='top' background='http://www.netland.com.cn/images/Top_GrayBar.gif' style='padding-top:3px'>");
	document.write("<table border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='229' ><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='15'></td>");
	document.write("<td><a href='/Market/'><font color='#FFFFFF'>今日报价</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Tech/Tech_Class.asp?CateID=15' target='_blank'><font color='#FFFFFF'>产品导购</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Products/Products_AllBrand.asp'><font color='#FFFFFF'>品牌列表</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Products/Products_AllClass.asp'><font color='#FFFFFF'>产品分类</font></a>");
	document.write("<font color='#FFFFFF'>  -   </font>");
	document.write("<a href='/News/News_Class.asp?CateID=2' target='_blank'><font color='#FFFFFF'>厂商信息</font></a>");
	document.write("</td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td bgcolor='#FFFFFF'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='1'></td></tr>");
	document.write("</table>");
}

function Top_News()
{
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr><td background='http://www.netland.com.cn/images/Top_BG.jpg'>");
	document.write("<table width='100%' border='0' cellpadding='0' cellspacing='0'>");
	document.write("<tr>");
	document.write("<td width='160' align='center'><img src='http://www.netland.com.cn/images/Top_Logo.gif' width='140' height='88'></td>");
	document.write("<td valign='bottom'>");
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='84' height='23' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/'>首 页</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Market/'>今日报价</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_MenuGray.gif' style='padding-top:4px'>");
	document.write("<a href='/News/'><font color='#FFFFFF'>资讯中心</font></a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Products/Default.asp'>产品中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8' style='padding-top:4px'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Tech/'>技术天地</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Trainning/'>培训认证</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Down/'>下载中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='7'><img src='http://www.netland.com.cn/images/BG_Menu_01.gif' width='7' height='23'></td>");
	document.write("<td background='http://www.netland.com.cn/images/BG_Menu_02.gif'>&nbsp;</td>");
	document.write("</tr>");
	document.write("</table></td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td height='22' valign='top' background='http://www.netland.com.cn/images/Top_GrayBar.gif' style='padding-top:3px'>");
	document.write("<table border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='352'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='15'></td>");
	document.write("<td ><a href='/News/News_Class.asp?CateID=1'><font color='#FFFFFF'>业界动态</font></a>");
	document.write("<font color='#FFFFFF'>  -   </font>");
	document.write("<a href='/News/News_Class.asp?CateID=2'><font color='#FFFFFF'>促销活动</font></a>");
	document.write("<font color='#FFFFFF'>  -   </font>");
	document.write("<a href='/News/News_Class.asp?CateID=4'><font color='#FFFFFF'>产品信息</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/News/News_Class.asp?CateID=3'><font color='#FFFFFF'>培训新闻</font></a>");
	document.write("</td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td bgcolor='#FFFFFF'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='1'></td></tr>");
	document.write("</table>");
}

function Top_Tech()
{
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr><td background='http://www.netland.com.cn/images/Top_BG.jpg'>");
	document.write("<table width='100%' border='0' cellpadding='0' cellspacing='0'>");
	document.write("<tr>");
	document.write("<td width='160' align='center'><img src='http://www.netland.com.cn/images/Top_Logo.gif' width='140' height='88'></td>");
	document.write("<td valign='bottom'>");
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='84' height='23' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/'>首 页</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Market/'>今日报价</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/News/'>资讯中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Products/Default.asp'>产品中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_MenuGray.gif' style='padding-top:4px'>");
	document.write("<a href='/Tech/'><font color='#FFFFFF'>技术天地</font></a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Trainning/'>培训认证</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Down/'>下载中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='7'><img src='http://www.netland.com.cn/images/BG_Menu_01.gif' width='7' height='23'></td>");
	document.write("<td background='http://www.netland.com.cn/images/BG_Menu_02.gif'>&nbsp;</td>");
	document.write("</tr>");
	document.write("</table></td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td height='22' valign='top' background='http://www.netland.com.cn/images/Top_GrayBar.gif' style='padding-top:3px'>");
	document.write("<table border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='342'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='15'></td>");
	document.write("<td>");
	document.write("<a href='/Tech/Tech_Class.asp?CateID=15' target='_blank'><font color='#FFFFFF'>产品导购</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Tech/Tech_Tech.asp'><font color='#FFFFFF'>技术文章</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Tech/Tech_Solu.asp'><font color='#FFFFFF'>解决方案</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Tech/Tech_Faq.asp'><font color='#FFFFFF'>FAQ</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Tech/Tech_Tip.asp'><font color='#FFFFFF'>每日一词</font></a>");
	document.write("</td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td bgcolor='#FFFFFF'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='1'></td></tr>");
	document.write("</table>");
}

function Top_Down()
{
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr><td background='http://www.netland.com.cn/images/Top_BG.jpg'>");
	document.write("<table width='100%' border='0' cellpadding='0' cellspacing='0'>");
	document.write("<tr>");
	document.write("<td width='160' align='center'><img src='http://www.netland.com.cn/images/Top_Logo.gif' width='140' height='88'></td>");
	document.write("<td valign='bottom'>");
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='84' height='23' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/'>首 页</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Market/'>今日报价</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/News/'>资讯中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Products/Default.asp'>产品中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Tech/'>技术天地</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Trainning/'>培训认证</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_MenuGray.gif' style='padding-top:4px'>");
	document.write("<a href='/Down/'><font color='#FFFFFF'>下载中心</font></a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='7'><img src='http://www.netland.com.cn/images/BG_Menu_01.gif' width='7' height='23'></td>");
	document.write("<td background='http://www.netland.com.cn/images/BG_Menu_02.gif'>&nbsp;</td>");
	document.write("</tr>");
	document.write("</table></td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td height='22' valign='top' background='http://www.netland.com.cn/images/Top_GrayBar.gif' style='padding-top:3px'>");
	document.write("<table border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='632'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='15'></td>");
	document.write("<td>");
	document.write("<a href='/Down/Down_Driver.asp'><font color='#FFFFFF'>驱动程序</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Down/Down_Software.asp'><font color='#FFFFFF'>应用软件</font></a>");
	document.write("</td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td bgcolor='#FFFFFF'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='1'></td></tr>");
	document.write("</table>");
}

function Top_Market()
{
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr><td background='http://www.netland.com.cn/images/Top_BG.jpg'>");
	document.write("<table width='100%' border='0' cellpadding='0' cellspacing='0'>");
	document.write("<tr>");
	document.write("<td width='160' align='center'><img src='http://www.netland.com.cn/images/Top_Logo.gif' width='140' height='88'></td>");
	document.write("<td valign='bottom'>");
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='84' height='23' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/'>首 页</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_MenuGray.gif' style='padding-top:4px'>");
	document.write("<a href='/Market/'><font color='#FFFFFF'>今日报价</font></a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/News/'>资讯中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Products/Default.asp'>产品中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Tech/'>技术天地</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Trainning/'>培训认证</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Down/'>下载中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='7'><img src='http://www.netland.com.cn/images/BG_Menu_01.gif' width='7' height='23'></td>");
	document.write("<td background='http://www.netland.com.cn/images/BG_Menu_02.gif'>&nbsp;</td>");
	document.write("</tr>");
	document.write("</table></td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td height='22' valign='top' background='http://www.netland.com.cn/images/Top_GrayBar.gif' style='padding-top:3px'>");
	document.write("<table border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='266'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='15'></td>");
	document.write("<td><a href='/Market/Market_AllClass.asp'><font color='#FFFFFF'>报价分类</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/News/News_Class.asp?CateID=2'><font color='#FFFFFF'>促销活动</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Products/'><font color='#FFFFFF'>产品介绍</font></a>");
	document.write("</td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td bgcolor='#FFFFFF'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='1'></td></tr>");
	document.write("</table>");
}

function Top_Trainning()
{
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr><td background='http://www.netland.com.cn/images/Top_BG.jpg'>");
	document.write("<table width='100%' border='0' cellpadding='0' cellspacing='0'>");
	document.write("<tr>");
	document.write("<td width='160' align='center'><img src='http://www.netland.com.cn/images/Top_Logo.gif' width='140' height='88'></td>");
	document.write("<td valign='bottom'>");
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='84' height='23' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/'>首 页</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Market/'>今日报价</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/News/'>资讯中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Products/Default.asp'>产品中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Tech/'>技术天地</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_MenuGray.gif' style='padding-top:4px'>");
	document.write("<a href='/Trainning/'><font color='#FFFFFF'>培训认证</font></a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Down/'>下载中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='7'><img src='http://www.netland.com.cn/images/BG_Menu_01.gif' width='7' height='23'></td>");
	document.write("<td background='http://www.netland.com.cn/images/BG_Menu_02.gif'>&nbsp;</td>");
	document.write("</tr>");
	document.write("</table></td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td height='22' valign='top' background='http://www.netland.com.cn/images/Top_GrayBar.gif' style='padding-top:3px'>");
	document.write("<table border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='207'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='15'></td>");
	document.write("<td><a href='/Trainning/Trainning_Intro.htm'><font color='#FFFFFF'>中心介绍</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Trainning/Trainning_Huawei_3Com.htm'><font color='#FFFFFF'>培训项目</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Trainning/Trainning_Custom_Network.htm'><font color='#FFFFFF'>定制培训</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Trainning/Trainning_Charge.htm'><font color='#FFFFFF'>收费标准</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Trainning/Trainning_Schedule.htm'><font color='#FFFFFF'>课程表</font></a>");
	document.write("<font color='#FFFFFF'>  -   </font>");
	document.write("<a href='/Trainning/Trainning_Signup.htm'><font color='#FFFFFF'>网上报名</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/Trainning/Trainning_Contact.htm'><font color='#FFFFFF'>联系我们</font></a>");
	document.write("</td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td bgcolor='#FFFFFF'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='1'></td></tr>");
	document.write("</table>");
}

function Top_About()
{
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr><td background='http://www.netland.com.cn/images/Top_BG.jpg'>");
	document.write("<table width='100%' border='0' cellpadding='0' cellspacing='0'>");
	document.write("<tr>");
	document.write("<td width='160' align='center'><img src='http://www.netland.com.cn/images/Top_Logo.gif' width='140' height='88'></td>");
	document.write("<td valign='bottom'>");
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='84' height='23' align='center' background='http://www.netland.com.cn/images/BG_MenuGray.gif' style='padding-top:4px'>");
	document.write("<a href='/'><font color='#FFFFFF'>首 页</font></a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Market/'>今日报价</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/News/'>资讯中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Products/Default.asp'>产品中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Tech/'>技术天地</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Trainning/'>培训认证</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Down/'>下载中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='7'><img src='http://www.netland.com.cn/images/BG_Menu_01.gif' width='7' height='23'></td>");
	document.write("<td background='http://www.netland.com.cn/images/BG_Menu_02.gif'>&nbsp;</td>");
	document.write("</tr>");
	document.write("</table></td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td height='22' valign='top' background='http://www.netland.com.cn/images/Top_GrayBar.gif' style='padding-top:3px'>");
	document.write("<table border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='188'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='15'></td>");
	document.write("<td><a href='/About/Contact.htm'><font color='#FFFFFF'>联系我们</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/About/AboutUS.htm'><font color='#FFFFFF'>关于我们</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/About/SiteMap.htm'><font color='#FFFFFF'>网站地图</font></a>");
	document.write("<font color='#FFFFFF'>  -  </font>");
	document.write("<a href='/About/Copyright.htm'><font color='#FFFFFF'>版权说明</font></a>");
	document.write("<font color='#FFFFFF'>  - </font>");
	document.write("<a href='/About/Privacy.htm'><font color='#FFFFFF'>隐私保护</font></a>");
	document.write("</td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td bgcolor='#FFFFFF'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='1'></td></tr>");
	document.write("</table>");
}

function Top_Other()
{
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr><td background='http://www.netland.com.cn/images/Top_BG.jpg'>");
	document.write("<table width='100%' border='0' cellpadding='0' cellspacing='0'>");
	document.write("<tr>");
	document.write("<td width='160' align='center'><img src='http://www.netland.com.cn/images/Top_Logo.gif' width='140' height='88'></td>");
	document.write("<td valign='bottom'>");
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='84' height='23' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/'>首 页</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Market/'>今日报价</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/News/'>资讯中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Products/Default.asp'>产品中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Tech/'>技术天地</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Trainning/'>培训认证</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='84' align='center' background='http://www.netland.com.cn/images/BG_Menu.gif' style='padding-top:4px'>");
	document.write("<a href='/Down/'>下载中心</a></td>");
	document.write("<td width='3'><img src='http://www.netland.com.cn/images/Blank.gif' width='3' height='8'></td>");
	document.write("<td width='7'><img src='http://www.netland.com.cn/images/BG_Menu_01.gif' width='7' height='23'></td>");
	document.write("<td background='http://www.netland.com.cn/images/BG_Menu_02.gif'>&nbsp;</td>");
	document.write("</tr>");
	document.write("</table></td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td height='22' valign='top' background='http://www.netland.com.cn/images/Top_GrayBar.gif' style='padding-top:3px'>");
	document.write("<table border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr>");
	document.write("<td width='250'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='15'></td>");
	document.write("</td></tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td bgcolor='#FFFFFF'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='1'></td></tr>");
	document.write("</table>");
}

function Bottom()
{
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr><td height='1' bgcolor='#FFFFFF'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='1'></td></tr>");
	document.write("<tr><td height='5' background='http://www.netland.com.cn/images/Top_GrayBar.gif'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='5'></td></tr>");
	document.write("<tr><td height='1'><img src='http://www.netland.com.cn/images/Blank.gif' width='1' height='1'></td></tr>");
	document.write("<tr><td height='22' bgcolor='#CC0000'>");
	document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr><td width='10'>&nbsp;</td>");
	document.write("<td>");
	document.write("<a href='/About/Copyright.htm' target='_blank'><font color='FFFFFF'>版权说明</font></a>");
	document.write("<font color='FFFFFF'> | </font><a href='/About/Privacy.htm' target='_blank'><font color='FFFFFF'>隐私保护</font></a>");
	document.write("<font color='FFFFFF'> | </font><a href='/About/SiteMap.htm' target='_blank'><font color='FFFFFF'>网站地图</font></a>");
	document.write("<font color='FFFFFF'> | </font><a href='/About/Contact.htm' target='_blank'><font color='FFFFFF'>联系我们</font></a>");
	document.write("<font color='FFFFFF'> | </font><a href='/About/AboutUS.htm' target='_blank'><font color='FFFFFF'>关于我们</font></a>");
	document.write("</td>");
	document.write("<td align='right'><font color='#FFFFFF'>Copyright 2002-2004网域科技版权所有. 经营许可证编号:粤ICP证030088</font></td>");
	document.write("<td width='10' align='right'>&nbsp;</td>");
	document.write("</tr>");
	document.write("</table></td></tr>");
	document.write("<tr><td height='50' valign='top'>");
	document.write("<table border='0' cellspacing='0' cellpadding='0'>");
	document.write("<tr><td rowspan='3' width='10'>&nbsp;</td><td height='5'> </td></tr>");
	document.write("<tr><td style='line-height:150%'>");
	document.write("产品销售热线：020-61073359   技术支持热线：020-61073333 转 2560； 售后服务热线：020-61073332<br>");
	document.write("联系邮箱：wx@vavic.com； 联系地址：广州市天河区工业园建工路15号首层</td>");
	document.write("</tr>");
	document.write("<tr><td height='30'>&nbsp;</td></tr>");
	document.write("</table></td></tr></table>");
}